version: '2'
services:
    platformseven-app:
        image: platformseven
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://platformseven-postgresql:5432/platformseven
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    platformseven-postgresql:
        extends:
            file: postgresql.yml
            service: platformseven-postgresql
